language: bash
sudo: required
services:
   - docker
before_install:
   - sudo apt-get update
   - sudo apt-get install -y docker-ce curl
   - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
   - sudo chmod +x /usr/local/bin/docker-compose

install:
   - docker-compose build
   - docker-compose up -d
   - docker-compose ps

script:
   - ./drupalinit.sh
   - curl http://localhost:8080/
