version: '3'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - "3306"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
     - "8080:80"
    depends_on:
     - db
